repos:
  - repo: local
    hooks:
      - id: sort-yaml-rules
        name: Sort rule YAML files
        language: python
        entry: python scripts/sort_yaml.py --no-format
        types: [yaml]
        files: ".*/rule\\.yml$"
        additional_dependencies: [ruamel.yaml]
        pass_filenames: true
